INTERNET_ACCESS: true # Set to true to enable internet access
MAX_SEARCH_RESULTS: 4 # Set the maximum search results for internet access DONT SET TOO HIGH

ALLOW_DM: true # Set to true to allow direct messages
SMART_MENTION: true # Set to true to enable smart mention feature

GPT_MODEL: gpt-3.5-turbo-0613 # Model used for chat completion

MAX_HISTORY: 8 # Set the maximum message history

PRESENCES_CHANGE_DELAY: 8 # Please note that the Presences Change Delay is measured in seconds. It is advisable not to set it too low, as doing so may result in your bot being rate-limited by Discord
AI_NSFW_CONTENT_FILTER: true # Enable NSFW AI detector to detect NSFW prompt on Imagine Command

LANGUAGE: en # Specify the language code (check 'lang' folder for valid codes)

INSTRUCTIONS: assist # Specify the instruction prompt to use (check 'instructions' folder for valid prompts)
# To add custom prompts, create a .txt file like 'custom.txt' in `instructions` folder and set INSTRUCTIONS as 'custom'

Discord: https://discord.com/invite/yz7r6v9d4E
Github: https://github.com/sonujana26/Discord-AI-bot/

TRIGGER:
  - chatbot
  - \
  - Bot
  - Help
  - Ai
  - Search
# Define the triggers that the bot should always respond to when in message

DISABLE_PRESENCE: false 
PRESENCES:
  - Earth's AI Assistant | Currently in {guild_count} servers
# List of different presences to be used

OCR_MODEL_URLS:
  - "https://api-inference.huggingface.co/models/microsoft/trocr-base-printed"
  - "https://api-inference.huggingface.co/models/nlpconnect/vit-gpt2-image-captioning"
# List of URLs for OCR models

BLACKLIST_WORDS:
  - nigga
  
# Blacklisted words for /Imagine command this is disabled if you enable AI_NSFW_CONTENT_FILTER
